export const checkboxes = [
  { id: "rental-app", label: "Rental Application", price: "Free" },
  { id: "credit-report", label: "Credit Report & Score*", price: "$39.99" },
  { id: "background-check", label: "Criminal background check*", price: "Included" },
  { id: "eviction-check", label: "Eviction related proceedings*", price: "Included" },
  { id: "income-verification", label: "Income verification report", price: "$10" },
];

export const states = [
  "AL",
  "AK",
  "AZ",
  "AR",
  "CA",
  "CO",
  "CT",
  "DE",
  "FL",
  "GA",
  "HI",
  "ID",
  "IL",
  "IN",
  "IA",
  "KS",
  "KY",
  "LA",
  "ME",
  "MD",
  "MA",
  "MI",
  "MN",
  "MS",
  "MO",
  "MT",
  "NE",
  "NV",
  "NH",
  "NJ",
  "NM",
  "NY",
  "NC",
  "ND",
  "OH",
  "OK",
  "OR",
  "PA",
  "RI",
  "SC",
  "SD",
  "TN",
  "TX",
  "UT",
  "VT",
  "VA",
  "WA",
  "WV",
  "WI",
  "WY",
];
